name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: pdo_pgsql
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Tests
        run: ./vendor/bin/pest

      # https://v4.tenancyforlaravel.com/postgres-rls/#creating-a-user-with-rls-policies
      - name: Create RLS Policies
        run: |
          php artisan migrate --force --database=pgsql_testing
          php artisan tenants:rls
        env:
          DB_CONNECTION: pgsql_testing
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_USERNAME: admin
          DB_PASSWORD: pass

      - name: Tenancy Tests
        run: ./vendor/bin/pest -c phpunit.tenancy.xml
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_USERNAME: admin
          DB_PASSWORD: pass
